version: "3.1"
services:
  api_service:
    container_name: app
    image: app
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgresql_db
  postgresql_db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: airport
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password